title: Karl MH LAI
logo: /assets/img/Karl_photo2.JPG
description: Karl M.H. Lai received his MSc degree in HKU in 2022. In 2019, he joined CLP Power as a protection engineer specializing in tieline, generator and IBR protection and control. He has a particular interest in advanced control, detection, filtering and estimation in IBR and HVDC systems.
show_downloads: false
theme: jekyll-theme-minimal
